[project]
name = "nano-llm"
version = "0.1.0"
description = "Project for experimenting with transformers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click",
    "torch",
    "tokenizers",
    "numpy>=2.3.4",
    "psutil",
    "PyYAML",
]
